plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bibledailyshine.videogenerator'
    compileSdk 36

    defaultConfig {
        applicationId 'com.bibledailyshine.videogenerator'

        minSdk 26
        targetSdk 36

        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false

            proguardFiles(
                    getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
            )
        }
    }
}
