plugins {
    id 'com.android.application'
}

android {
    namespace 'com.bibledailyshine.videogenerator'
    compileSdk 35

    defaultConfig {
        applicationId "com.bibledailyshine.videogenerator"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "1.0"

        ndk {
            abiFilters "arm64-v8a"
        }
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.7.1'

    implementation 'dev.ffmpegkit-maintained:kokoro-android:0.1.0'
}
