plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.bibledailyshine.generator'

    compileSdk 35

    defaultConfig {
        applicationId 'com.bibledailyshine.generator'

        minSdk 24
        targetSdk 35

        versionCode 1
        versionName '1.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false

            proguardFiles(
                    getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
            )
        }

        debug {
            minifyEnabled false
        }
    }

    packaging {
        resources {
            excludes += [
                    '/META-INF/{AL2.0,LGPL2.1}',
                    '/META-INF/DEPENDENCIES',
                    '/META-INF/LICENSE',
                    '/META-INF/LICENSE.txt',
                    '/META-INF/NOTICE',
                    '/META-INF/NOTICE.txt'
            ]
        }
    }

    ndkVersion '27.2.12479018'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_21
        targetCompatibility JavaVersion.VERSION_21
    }

    kotlinOptions {
        jvmTarget = '21'
    }
}

dependencies {

    implementation 'androidx.core:core-ktx:1.15.0'

    implementation 'androidx.appcompat:appcompat:1.7.0'

    implementation 'io.github.minorlai:ffmpeg-kit-16kb:6.1.2'
}
